# Generated by Django 2.2 on 2021-04-13 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_portfolio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='imagenes',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='privacidades',
        ),
        migrations.CreateModel(
            name='Portfolio_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacidad', models.IntegerField()),
                ('imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gallery.Image')),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gallery.Portfolio')),
            ],
        ),
    ]
