# Generated by Django 2.2 on 2021-04-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210413_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='imagenes',
            field=models.ManyToManyField(through='gallery.Portfolio_Image', to='gallery.Image'),
        ),
    ]
