# Generated by Django 2.2 on 2021-04-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_portfolio_imagenes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='imagenesInv',
            field=models.ManyToManyField(related_name='imagenesInv', through='gallery.Portfolio_Image', to='gallery.Image'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='imagenesPublicas',
            field=models.ManyToManyField(related_name='imagenesPublicas', to='gallery.Image'),
        ),
    ]
